// In this file you can specify the trial data for your experiment

const practice_trials = {
    key_press: [
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/13_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/13_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/13_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/13_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/14_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/14_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/14_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/14_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/15_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/15_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/15_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/15_150_different.jpg",
            expected: "different",
            angle: 150,
        }
    ]
};

const main_trials = {
    key_press: [
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/1_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/1_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/1_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/1_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/2_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/2_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/2_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/2_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/3_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/3_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/3_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/3_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/4_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/4_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/4_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/4_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/5_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/5_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/5_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/5_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/6_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/6_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/6_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/6_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/7_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/7_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/7_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/7_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/8_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/8_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/8_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/8_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/9_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/9_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/9_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/9_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/10_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/10_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/10_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/10_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/11_50_same.jpg",
            expected: "same",
            angle: 50
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/11_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/11_150_same.jpg",
            expected: "same",
            angle: 150
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/11_150_different.jpg",
            expected: "different",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/12_50_same.jpg",
            expected: "same",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/12_50_different.jpg",
            expected: "different",
            angle: 50,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/12_150_same.jpg",
            expected: "same",
            angle: 150,
        },
        {
            question: "Are the objects different or the same?",
            key1: "q",
            key2: "p",
            q: "same",
            p: "different",
            picture: "images/12_150_different.jpg",
            expected: "different",
            angle: 150,
        }
    ]
};
